# Generated by Django 5.0.6 on 2024-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic_8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='book/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
