# Generated by Django 5.0.6 on 2024-07-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practic_8', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
