# Generated by Django 5.0.6 on 2024-07-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic_3', '0002_rename_name_book_name_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practic_3.author'),
        ),
    ]
